theme: jekyll-theme-minimal
title: Jeonghoon Kwak
description: <p><b>Ph. D. candidate </b><br>Department of Multimedia Engineering, Dongguk University-Seoul, Seoul, Korea</p>
show_downloads: false
email: jeonghoon.k09@gmail.com